"""empty message

Revision ID: 4d8638827c8e
Revises: f8626a899800
Create Date: 2022-01-24 14:55:27.912961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8638827c8e'
down_revision = 'f8626a899800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('data2', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'data2')
    # ### end Alembic commands ###
