"""empty message

Revision ID: eb25af6e40a7
Revises: 78f759a1d5eb
Create Date: 2022-01-27 13:47:13.719560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb25af6e40a7'
down_revision = '78f759a1d5eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_position', table_name='user')
    op.drop_column('user', 'position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('position', sa.VARCHAR(length=128), nullable=True))
    op.create_index('ix_user_position', 'user', ['position'], unique=False)
    # ### end Alembic commands ###
